services:
  - type: web
    name: soulengine-backend
    env: docker
    plan: free
    region: oregon
    branch: main
    repo: https://github.com/Ataraxicat-777/soulengine-openrouter
    autoDeploy: true
